### PR TITLE
neovim to Neovim

### PR DESCRIPTION
**Pull request by tani**
I am sorry that I found a severe problem with this repository. I would like to help you solve this problem if you would not mind spending an amount of time. The following is the description of this problem.

To participate in the hacktoberfest, I searched suspicious repositories to contribute to the open-source community.
Then, I found this repository. The code is thoroughly tested, and wonderfully organized code. Thus, it looks clean with no bugs.
However, I believe that the repository is suspicious; it might contain a potential bug. Honestly, this bug hunting is the most complex challenge I have ever tried.

At first, I studied your code in autoload folder. Amazingly, the code is perfect, and there is no ugly code even you write it in VimL. So I estimate you are a vim specialist. 

Next, I read the LICENSE file. I suggest another license like CC0 or the Unlisence because the MIT license requires the copyright notice to use your code in other projects. So the MIT license is too strict license for your project. However, this is not a bug. 

Finally, I found a severe issue in README. I first considered telling you privately by e-mail with PGP or other security tools because it causes a significant impact on your project. Still, I have decided to send this pull request to tell you immediately. Please quickly merge it before other Neovim users finding you.

The issue is a typo.

Best wishes,

### CODE REVIEW

**Comment by michaelb** [comment]
You make some points 👍

However, I'll keep the MIT license. It's unlikely my plugin would be used in another project, since the features are rather user-focused (rather than providing an API). Moreover, it only entails the subsantial use of this project to be licensed under MIT, so including do-nothing.vim does not restrict the licensing of the containing projet as a whole.


I'll need some time to thoroughly review your work, please understand that you brought in a substantial amount of work that changed the content of most files in this repository. I'll need to focus a little to get back into this project...

Thank you for your contribution!

**Comment by michaelb** [comment]
Hi, as another user pointed out, there is another typo in the project's README
(ressource->resource)

As it falls under the scope of this PR, would you be kind enough to include a fix?

It's very important to minimize the number of breaking changes brought to the end-user

**Comment by tani** [comment]
Thank you very much for your suggestion. My pull request was a change to a visual problem, a case change, but the genius person who found the problem, incredibly, pointed out a grammatical error in English words. I am now determined to work hard to make such linguistically suggestive improvements. Now, I am concerned about two things that we adopt changes to contain essentially different problems (visual problem vs grammatical problem) and that this change will consume more and more of your valuable time. Please take it easy and work at your own pace.

**Comment by michaelb** [comment]
Thank you very much for your involvement in this project and the care you display in your contribution process.

You responded to the change request so quickly I can't help but worry too, so let's both take it easy okay? I don't want neither of us to burn-out, and while I, as a project maintainer, am used to rabbit-holes sucking away most of my time, I would rather not lose such a wonderful contributor to the depths of open-source.

As for the contents of the PR itself, i've only been able to take a glance for now, but it looks extremely clean.

We shouldn't concern too much with your PR  addressing two different problems of the same type, separating into different commits is probably enough. do-nothing.vim is essentially a medium-sized project that don't warrant yet such commitment to project quality. Would your PR be on a much bigger project such as [this one](https://github.com/tjdevries/literally_empty), then yes doing two separate PRs would be the right thing to do

I look forward to merging your changes!

**Pull request merged**
