### PR TITLE
Fix critical bugs that may affect performance or productivity

### PR DESCRIPTION
**Pull request by mattn**
Thanks your great Vim plugin. I installed this Vim plugin without any performance delays. Cool.

I found critical bugs that may affect performance or productivity

### CODE REVIEW

**Comment by michaelb** [comment]
Though this is indeed a typo, I'm afraid this will not affect performance or producivity whatever it means.

And a contrario of the earlier PR, you made little efforts to be funny or anything so this is bordeline spam....

I'm sorry guy/girl but this is not the spirit of Hacktoberfest

**Comment by mattn** [comment]
Very sad. But I'm looking forward to the pull-request from someone who makes the same fix as this one. And it will be crazy funny. thank you.

**Comment by michaelb** [comment]
Don't hesitate to get a look at the hacktoberfest PR' guideline and happy hacking :-) 
https://hacktoberfest.digitalocean.com/resources

**Comment by mattn** [comment]
Thanks your advices. BTW you had typo. s/bordeline/borderline/. See you.

**Pull request closed without merging**
